@startuml

title __DB's Class Diagram__\n

  namespace com.example.shanifinor_project {
    namespace model.db {
      class com.example.shanifinor_project.model.db.Repository {
          {static} - instance : Repository
          - observers : ArrayList<Observer>
          - users : Map<String, UserDao>
          {static} + getInstance()
          + getUsers()
          + register()
          + unregister()
          - Repository()
          - notifyObservers()
      }
    }
  }
  

  namespace com.example.shanifinor_project {
    namespace model.db {
      class com.example.shanifinor_project.model.db.UserDao {
          - databaseOpenSquares : List<String>
          - email : String
          - guessedAnswer : String
          - icon : String
          - name : String
          - numOfWin : int
          - place : int
          - placeChosenFromSuggestedString : List<Integer>
          - stars : int
          - suggestedString : String
          + UserDao()
          + UserDao()
          + UserDao()
          + UserDao()
          + getDatabaseOpenSquares()
          + getEmail()
          + getGuessedAnswer()
          + getIcon()
          + getName()
          + getNumOfWin()
          + getPlace()
          + getPlaceChosenFromSuggestedString()
          + getStars()
          + getSuggestedString()
          + setDatabaseOpenSquares()
          + setEmail()
          + setGuessedAnswer()
          + setIcon()
          + setName()
          + setNumOfWin()
          + setPlace()
          + setPlaceChosenFromSuggestedString()
          + setStars()
          + setSuggestedString()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
